const home = {
  en: {
    featuredProducts: "Featured Products",
    latestProducts: "Latest Products",
    price: "Price",
    location: "Location",
    category: "Category",
    postedOn: "Posted on",
    forSale: "For Sale",
    forRent: "For Rent",
    listedBy: "Listed by",
    details: "Details",
    year: "Year",
    openInGoogleMaps: "Open in Google Maps",
    close: "Close",
    chooseLocation: "Choose Location",
    searchLocationPlaceholder: "Search location...",
    noLocationsFound: "No locations found.",
    search: "Search",
    noProductsFound: "No products found.",
    minPrice: "Min Price",
    maxPrice: "Max Price",
  },
  ar: {
    featuredProducts: "منتجات مميزة",
    latestProducts: "أحدث المنتجات",
    price: "السعر",
    location: "الموقع",
    category: "الفئة",
    postedOn: "تاريخ النشر",
    forSale: "للبيع",
    forRent: "للإيجار",
    listedBy: "تم النشر بواسطة",
    details: "تفاصيل",
    year: "السنة",
    openInGoogleMaps: "افتح في خرائط جوجل",
    close: "إغلاق",
    chooseLocation: "اختر الموقع",
    searchLocationPlaceholder: "ابحث عن موقع...",
    noLocationsFound: "لم يتم العثور على مواقع.",
    search: "بحث",
    noProductsFound: "لم يتم العثور على منتجات.",
    minPrice: "السعر الأدنى",
    maxPrice: "السعر الأقصى",
  },
};

export default home;
